name: wallet_connect_android
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  wallet_connect_platform_interface:
    path: ../wallet_connect_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: wallet_connect
    platforms:
      android:
        package: io.tokoin.wallet.connect
        pluginClass: WalletConnectAndroidPlugin
        dartPluginClass: WalletConnectAndroid
