name: wallet_connect_ios
description: iOS implementation of the wallet_connect plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

flutter:
  plugin:
    implements: wallet_connect
    platforms:
      ios:
        pluginClass: WalletConnectPlugin
        dartPluginClass: WalletConnectIOS

dependencies:
  flutter:
    sdk: flutter
  wallet_connect_platform_interface:
    path: ../wallet_connect_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.1.0
