name: wallet_connect
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wallet_connect_android:
    git:
      url: git@github.com:tokoinofficial/wallet_connect.git
      path: wallet_connect_android
  wallet_connect_platform_interface:
    git:
      url: git@github.com:tokoinofficial/wallet_connect.git
      path: wallet_connect_platform_interface
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: wallet_connect_android

